-- ============================================================
--  Datos iniciales. GENERADO por scripts/generar-datos-iniciales.ts
--  desde src/config y src/content. No editar a mano.
--  No pisa datos existentes: después de esto, se edita desde /admin.
-- ============================================================

insert into public.servicios
  (slug, categoria, nombre, titulo_descripcion, descripcion, incluye, duracion_texto, duracion_minutos, detalles, destacado, precio, orden)
values
  ('semipermanente', 'manicuria'::public.categoria_servicio, 'Semipermanente manos y pies', 'Descripción', 'Esmaltado de larga duración que mantiene el brillo y el color intactos durante semanas, sin descascararse. Ideal para uñas naturales que buscan un acabado prolijo y luminoso.', array['Limado y forma', 'Trabajo de cutículas', 'Esmaltado semipermanente en el color que elijas', 'Hidratación final']::text[], '1 h 30 min aprox.', 90, '[{"titulo":"Mantenimiento / frecuencia","texto":"Se recomienda renovar cada 2 a 3 semanas para mantener las uñas sanas y prolijas."}]'::jsonb, null, null, 10),
  ('kapping', 'manicuria'::public.categoria_servicio, 'Kapping', 'Descripción', 'Una capa protectora (gel o polygel) sobre la uña natural que la fortalece y ayuda a que crezca sin quebrarse. Perfecto si querés lucir tus propias uñas, más resistentes.', array['Preparación de la uña natural', 'Aplicación de capa protectora', 'Esmaltado semipermanente', 'Hidratación final']::text[], '1 h 45 min aprox.', 105, '[{"titulo":"Mantenimiento / frecuencia","texto":"Service cada 3 semanas aproximadamente, según el crecimiento de tus uñas."}]'::jsonb, null, null, 20),
  ('esculpidas', 'manicuria'::public.categoria_servicio, 'Esculpidas', 'Descripción', 'Extensión de uñas modelada a mano para lograr el largo y la forma que soñás, con un acabado natural, elegante y resistente.', array['Preparación de la uña natural', 'Esculpido con el largo y la forma elegidos', 'Esmaltado semipermanente', 'Hidratación final']::text[], '2 h 30 min aprox.', 150, '[{"titulo":"Mantenimiento / frecuencia","texto":"Service cada 3 semanas para mantener la estructura y la estética de la uña."}]'::jsonb, null, null, 30),
  ('lifting', 'rostro'::public.categoria_servicio, 'Lifting de pestañas', '¿Qué es?', 'Un tratamiento que eleva y curva tus pestañas naturales desde la raíz, abriendo la mirada sin necesidad de extensiones ni arqueador.', array['Limpieza de la zona', 'Lifting con productos específicos', 'Tinte de pestañas', 'Nutrición final']::text[], '1 h aprox.', 60, '[{"titulo":"Cuidados","texto":"No mojar las pestañas durante las primeras 24 horas y evitar productos oleosos en la zona."}]'::jsonb, null, null, 40),
  ('laminado', 'rostro'::public.categoria_servicio, 'Laminado de cejas', '¿Qué es?', 'Alisa y peina los vellos de las cejas en la dirección deseada para lograr un efecto más tupido, prolijo y definido durante semanas.', array['Diagnóstico de la ceja', 'Laminado', 'Perfilado', 'Nutrición final']::text[], '1 h aprox.', 60, '[{"titulo":"Cuidados","texto":"No mojar las cejas durante las primeras 24 horas y peinarlas a diario para mantener la forma."}]'::jsonb, null, null, 50),
  ('diseno', 'rostro'::public.categoria_servicio, 'Diseño y perfilado', '¿Qué es?', 'Un diseño de cejas pensado para tu rostro: se estudian tus proporciones para definir una forma armónica y natural.', array['Visagismo / estudio de proporciones', 'Diseño personalizado', 'Perfilado']::text[], '45 min aprox.', 45, '[{"titulo":"Cuidados","texto":"Evitar exposición solar directa y maquillaje en la zona durante algunas horas."}]'::jsonb, null, null, 60),
  ('sombreado', 'rostro'::public.categoria_servicio, 'Sombreado', '¿Qué es?', 'Un tinte suave que rellena y da profundidad a las cejas, logrando un efecto de maquillaje natural.', array['Diseño previo', 'Aplicación de sombreado', 'Perfilado final']::text[], '45 min aprox.', 45, '[{"titulo":"Cuidados","texto":"No mojar la zona durante las primeras horas y evitar exfoliantes sobre las cejas."}]'::jsonb, null, null, 70),
  ('carta-natal', 'astrologia'::public.categoria_servicio, 'Carta natal', '¿Qué es?', 'Una lectura y consultoría de tu carta natal: el mapa del cielo en el momento exacto de tu nacimiento. Un espacio para conocer tus potenciales, tus desafíos y tus ciclos con una mirada amorosa y consciente.', array['Análisis previo y personalizado de tu carta', 'Sesión de lectura y consultoría', 'Espacio para tus preguntas']::text[], '1 h 30 min de sesión aprox.', 90, '[{"titulo":"Modalidad","texto":"[COMPLETAR: presencial / online por videollamada]"},{"titulo":"Tiempos","texto":"Una vez realizada la reserva, la sesión se pacta aproximadamente 7 días después. Ese tiempo es necesario para analizar tu carta en profundidad antes del encuentro. Para armarla vas a necesitar tu fecha, hora exacta y lugar de nacimiento."}]'::jsonb, null, null, 80),
  ('revolucion-solar', 'astrologia'::public.categoria_servicio, 'Revolución solar', '¿Qué es?', 'La carta que se levanta cada año alrededor de tu cumpleaños, cuando el Sol vuelve a la posición exacta en la que estaba al nacer. Muestra los temas, oportunidades y aprendizajes de tu nuevo ciclo anual.', array['Análisis personalizado de tu revolución solar', 'Relación con tu carta natal', 'Sesión de lectura y espacio para preguntas']::text[], '1 h 15 min de sesión aprox.', 75, '[{"titulo":"Modalidad","texto":"[COMPLETAR: presencial / online por videollamada]"},{"titulo":"Análisis personalizado","texto":"Cada revolución solar se prepara de manera individual, a partir de tus datos de nacimiento y del lugar donde vas a pasar tu cumpleaños."}]'::jsonb, null, null, 90),
  ('tarot-astrologico', 'astrologia'::public.categoria_servicio, 'Tarot astrológico', '¿Qué es?', 'Una lectura de tarot que integra el simbolismo de los planetas y los signos para responder tus preguntas con mayor profundidad y claridad.', array['Hasta 3 preguntas', 'Tirada y lectura astrológica', 'Orientación sobre cada respuesta']::text[], '45 min aprox.', 45, '[{"titulo":"Modalidad","texto":"[COMPLETAR: presencial / online por videollamada]"}]'::jsonb, 'El precio incluye hasta 3 preguntas.', null, 100)
on conflict (slug) do nothing;

insert into public.configuracion (clave, valor) values
  ('sitio', '{"frase":"Belleza delicada, rituales de cuidado y lecturas del cielo.","ubicacion":{"direccion":"[COMPLETAR DIRECCIÓN]","barrio":"Parque Chas","ciudad":"CABA","indicaciones":"[COMPLETAR: timbre, piso, colectivos/subte cercanos, estacionamiento]"},"contacto":{"whatsapp":"[COMPLETAR WHATSAPP]","whatsappVisible":"[COMPLETAR WHATSAPP]","email":"[COMPLETAR EMAIL]","instagram":"[COMPLETAR INSTAGRAM]"},"horarios":[{"dias":"Lunes a viernes","horas":"[COMPLETAR]"},{"dias":"Sábados","horas":"[COMPLETAR]"},{"dias":"Domingos","horas":"[COMPLETAR]"}],"banco":{"alias":"[ALIAS]","cbu":"[CBU]","titular":"[TITULAR]","cuit":"[CUIT]"},"condicionesCancelacion":"[COMPLETAR: con cuánta anticipación se puede reprogramar/cancelar y qué pasa con la seña]","avisoAstrologia":"Una vez confirmada tu reserva recibirás información sobre los tiempos necesarios para preparar y analizar tu carta.","google":{"linkResenas":"[COMPLETAR LINK RESEÑAS GOOGLE]","linkEscribirResena":"[COMPLETAR LINK ESCRIBIR RESEÑA]"}}'::jsonb),
  ('textos', '{"sobreMi":{"titulo":"Sobre mí","saludo":"Hola, soy Sofi.","parrafos":["[COMPLETAR: quién sos, en primera persona y con tus palabras. Por ejemplo, desde cuándo trabajás en esto y qué te llevó a empezar.]","Manicuría — [COMPLETAR: tu recorrido y experiencia con las uñas: técnicas que dominás, años de práctica, lo que más disfrutás.]","Rostro — [COMPLETAR: tu trabajo con pestañas y cejas: formación, enfoque, cómo cuidás la naturalidad de cada rostro.]","Astrología — [COMPLETAR: tu formación y recorrido en astrología: dónde estudiaste, desde cuándo, cómo la vivís.]","[COMPLETAR: tu manera de trabajar y tu filosofía. Qué querés que sienta cada persona que pasa por tu espacio.]"],"firma":"Sofi"},"servicios":{"titulo":"Servicios","bajada":"Tres maneras de cuidarte, un mismo espacio."},"categorias":{"manicuria":{"titulo":"Manicuría","bajada":"Uñas prolijas, delicadas y duraderas, hechas con tiempo y detalle."},"rostro":{"titulo":"Rostro","bajada":"Miradas que se iluminan con naturalidad: pestañas y cejas a tu medida."},"astrologia":{"titulo":"Astrología","bajada":"Un encuentro con tu cielo para mirarte con más claridad."}},"contacto":{"titulo":"Contacto","bajada":"¿Tenés dudas sobre algún servicio o querés coordinar un turno? Escribime, me encanta conversar."},"resenas":{"titulo":"Reseñas","bajada":"Lo que cuentan quienes ya pasaron por el espacio."}}'::jsonb),
  ('reservas', '{"senaPorcentaje":50,"intervaloMinutos":30,"anticipacionMinimaHoras":12,"horizonteDias":60,"maxReservasPorHora":3}'::jsonb)
on conflict (clave) do nothing;
